### ISSUE TITLE
Submarines of Deleted and Ignored Characters Reappearing

### ISSUE THREAD

**Issue by WalkerWatch** [Infiziert90/SubmarineTracker#18]
Repro Steps #1.

1. Delete Character (s) from the Manage menu, and add character(s) to Ignore
2. Enter the house of the deleted character.
3. Enter the Company Workshop
4. Previously deleted character(s) as well as ignored character(s) subs will appear in the Submarine Tracker Overlay.

Repro Steps #2.

1. Delete Character (s) from the Manage menu, and add character(s) to Ignore
2. Enter the house of a separate character.
3. Enter the Company Workshop
4. Previously deleted character(s) as well as ignored character(s) subs will appear in the Submarine Tracker Overlay.

**Comment by Infiziert90** [comment]
Deletion is currently "disabled" , it will come back at some point in the near future

**Comment by Infiziert90** [comment]
Fixed
