### ISSUE TITLE
Using on Dalamud in CN can cause the game to crash and has been automatically disabled by the Dalamud. Please fix,thank you

### ISSUE THREAD

**Issue by LLovelyMrzheng** [Infiziert90/SubmarineTracker#22]
![image](https://github.com/user-attachments/assets/cff97cae-e704-4750-9fc7-2f8571817000)

**Comment by Infiziert90** [comment]
This version is only maintained for global, please ask your CN people to maintain their own version with the hooks or PR a fixed version for the CN one
