### ISSUE TITLE
/sbuilder menu -> Best Exp tab instant calculation issue

### ISSUE THREAD

**Issue by Dedoooo** [Infiziert90/SubmarineTracker#3]
Not a fan of having to wait for a calculation that i didn't initiate, would be great if there was a button to start because it immediately starts on an area that i'm not interested in.

**Comment by Infiziert90** [comment]
Possible to add an option for that

Not intended to make it a default as calculations should be fast enough to just ignore for most people

**Comment by Infiziert90** [comment]
You already have that in the tracker for each FC

/sloot is for all FCs combined
