### ISSUE TITLE
Bug in the Builder < Best Exp tab 

### ISSUE THREAD

**Issue by ZNautilus** [Infiziert90/SubmarineTracker#8]
When "Auto Select Current Submarine" is checked and using the "Best Exp" menu if two submarines are the same level, for example rank 89, then when switching from one sub to the next in-game the suggested destinations will give the message "No route found, check speed and range ... ". This message will persist when selecting the first sub again or any other submarine of the same level, including submarines on different worlds.

Thus far the only way I have found to work around this bug is by selecting another submarine map in the Best Exp dropdown menu, letting the destinations load, and the switching back to the desired map.

![7e9ad73b154892e1702dfa8888566b05](https://github.com/Infiziert90/SubmarineTracker/assets/142350089/61ec86f5-e681-43d3-bedc-a5a99ff79e13)

**Comment by Infiziert90** [comment]
If you still have this issue happening after the update, pls comment here

**Comment by ZNautilus** [comment]
Bug appears to still be present. Updated: Bug can also be recreated by using the aforementioned settings and clicking on a submarine via in-game, backing to the sub selection, and clicking the same submarine again. Hope that helps

**Comment by Infiziert90** [comment]
The update isn't live yet ^^

**Comment by Infiziert90** [comment]
Update is live now, you should get an update prompt whenever you start your game again
