### ISSUE TITLE
[Feature Request/Issue] Loot Export

### ISSUE THREAD

**Issue by wiiaboo** [Infiziert90/SubmarineTracker#9]
"To" datepicker on Custom Loot Overview - Export has some weird behavior
- [ ]  Leaving "To" empty/default does not include today's voyages
- [ ]  Setting "To" manually to "2023/08/18" (following the placeholder format, which is maybe hardcoded and does not use the User's Date Format set in Configuration) does not include today's voyages
- [x]  Clicking ♻️ sets "To" to "2023-08-18" which does include today's voyages
- [x] Setting "To" manually to "2023-08-18" includes today's voyages
- [x] Setting "To" using datepicker widget to today includes today's voyages

Additionally some QoL feature requests:
1. Preserve settings for loot export across sessions (i.e. Exclude Date and Output Folder, "From"/"To" probably shouldn't be saved)
2. "Export to clipboard" button in addition to existing one?

**Comment by Infiziert90** [comment]
> "To" datepicker on Custom Loot Overview - Export has some weird behavior
> 
> * [ ]   Leaving "To" empty/default does not include today's voyages
> * [ ]   Setting "To" manually to "2023/08/18" (following the placeholder format, which is maybe hardcoded and does not use the User's Date Format set in Configuration) does not include today's voyages
> * [x]   Clicking ♻️ sets "To" to "2023-08-18" which does include today's voyages
> * [x]  Setting "To" manually to "2023-08-18" includes today's voyages
> * [x]  Setting "To" using datepicker widget to today includes today's voyages


I will look into it

But yeah the issue that you have with setting the date is easy to explain

If you pick or manually input a date the time is set to 00:00:00, while the Reset button sets it to "Now", thats why you have this weird behavior

I will prolly just set the time to 23:59:59

Why it doesn't work with an empty field is weird, as it does the same as the Reset button...

**Comment by Infiziert90** [comment]
Could you confirm that your input fields are actually "2023-08-18" with this format?

**Comment by Infiziert90** [comment]
Should work as intended now, if there is still issues after the update, pls comment here again
